#!/bin/bash

# genmon script to display the status of ProtonVPN
protonvpn -s | awk '/Status:/ {print($2)}' | grep -q Dis && echo "<img>$HOME/.pvpnmon/disconnected.svg</img>" || echo "<img>$HOME/.pvpnmon/connected.svg</img>"

